"""empty message

Revision ID: 0f41c4fbe189
Revises: c14d1efb69f5
Create Date: 2020-10-20 11:00:37.513897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f41c4fbe189'
down_revision = 'c14d1efb69f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_title_key', 'movie', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movie_title_key', 'movie', ['title'])
    # ### end Alembic commands ###
